# Generated by Django 4.2.8 on 2024-05-21 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_airecommend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='character',
            field=models.CharField(max_length=500),
        ),
    ]
